## Dense Layers

### Shapes of Dense Layers

In [4]:
import tensorflow as tf
from tensorflow.keras.layers import Dense

N, n_feature = 8, 10
X = tf.random.normal(shape=(N, n_feature)) # X는 X.transpose를 의미

n_neuron = 3
dense = Dense(units=n_neuron, activation='sigmoid') # 한개의 layer에 3개의 뉴런을 가짐
Y = dense(X)

W, B = dense.get_weights()

print('***** Input/Weight/Bias *****')
print('X : ', X.shape)
print('W : ', W.shape)
print('B : ', B.shape)
print('Y : ', Y.shape)

***** Input/Weight/Bias *****
X :  (8, 10)
W :  (10, 3)
B :  (3,)
Y :  (8, 3)


### Output Calculations

In [7]:
import numpy as np
import tensorflow as tf
from tensorflow.math import exp
from tensorflow.linalg import matmul
from tensorflow.keras.layers import Dense

N, n_feature = 4, 10
X = tf.random.normal(shape=(N, n_feature))

n_neuron = 3
dense = Dense(units=n_neuron, activation='sigmoid') # 한개의 layer에 3개의 뉴런을 가짐
Y_tf = dense(X)

W, B = dense.get_weights()
print('Y(tensorflow) \n', Y_tf.numpy())

# calculate with matrix multiplication
z = matmul(X, W) + B
y_man = 1 / (1 + exp(-z))
print('Y(manual) \n', y_man.numpy())

# calculate with dot products
Y_man_vec = np.zeros(shape=(N, n_neuron))
for x_idx in range(N):
    x = X[x_idx]
    
    for nu_idx in range(n_neuron):
        w, b = W[:, nu_idx], B[nu_idx]
        
        z = tf.reduce_sum(x*w) + b
        a = 1/(1 + np.exp(-z))
        Y_man_vec[x_idx, nu_idx] = a
        
print('Y(with dot products)\n ', Y_man_vec)

Y(tensorflow) 
 [[0.5354668  0.280311   0.29505935]
 [0.1262378  0.26131862 0.24623986]
 [0.73066247 0.90359235 0.5680011 ]
 [0.31405592 0.20042019 0.59765637]]
Y(manual) 
 [[0.5354668  0.280311   0.29505935]
 [0.1262378  0.26131862 0.24623986]
 [0.73066247 0.90359235 0.5680011 ]
 [0.31405592 0.20042019 0.59765637]]
Y(with dot products)
  [[0.53558732 0.28043956 0.29501842]
 [0.12619491 0.26130881 0.24628956]
 [0.73062652 0.90354253 0.56791106]
 [0.31397478 0.2004457  0.59775943]]


## Cascaded Dense  Layers

### Shapes of Cascaded Dense Layers

In [13]:
import tensorflow as tf

from tensorflow.keras.layers import Dense

N, n_feature = 4, 10

X = tf.random.normal(shape=(N, n_feature))

n_neurons = [3,5]
dense1 = Dense(units=n_neurons[0], activation='sigmoid')
dense2 = Dense(units=n_neurons[1], activation='sigmoid')

# forward propagation
A1 = dense1(X)
Y = dense2(A1)

# get weight/bias
W1, B1 = dense1.get_weights()
W2, B2 = dense2.get_weights()

print('X : {}\n'.format(X.shape))

print('W1 : ', W1.shape)
print('B1 : ', B1.shape)
print('A1 : {}\n'.format(A1.shape))

print('W2 : ', W2.shape)
print('B2 : ',B2.shape)
print('Y : {}'.format(Y.shape))

X : (4, 10)

W1 :  (10, 3)
B1 :  (3,)
A1 : (4, 3)

W2 :  (3, 5)
B2 :  (5,)
Y : (4, 5)


### Dense Layers with Python List

In [15]:
import tensorflow as tf

from tensorflow.keras.layers import Dense

N, n_feature = 4, 10

X = tf.random.normal(shape=(N, n_feature))

n_neurons = [10, 20 ,30, 40, 50, 60, 70, 80, 90, 100]

dense_layers = []

for n_neuron in n_neurons:
#     print(n_neuron)
    dense = Dense(units=n_neuron, activation='relu')
    dense_layers.append(dense)

print('Input : ', X.shape)
for dense_idx, dense in enumerate(dense_layers):
    X = dense(X)
    print("After dense layer : ", dense_idx+1)
    print(X.shape, '\n')

Y = X

Input :  (4, 10)
After dense layer :  1
(4, 10) 

After dense layer :  2
(4, 20) 

After dense layer :  3
(4, 30) 

After dense layer :  4
(4, 40) 

After dense layer :  5
(4, 50) 

After dense layer :  6
(4, 60) 

After dense layer :  7
(4, 70) 

After dense layer :  8
(4, 80) 

After dense layer :  9
(4, 90) 

After dense layer :  10
(4, 100) 



### Output Calculations

In [3]:
import tensorflow as tf

from tensorflow.keras.layers import Dense
from tensorflow.math import exp
from tensorflow.linalg import matmul

N, n_feature = 4, 10
X = tf.random.normal(shape=(N, n_feature))
X_cp = tf.identity(X) # X를 copy (깊은복사)

n_neurons = [3, 4, 5]

dense_layers = []
for n_neuron in n_neurons:
    dense = Dense(units=n_neuron, activation='sigmoid')
    dense_layers.append(dense)

print('Input : ', X.shape)

# forward propagation (tensorflow)
W, B = [], []
for dense_idx, dense in enumerate(dense_layers):
    X = dense(X)
    w, b = dense.get_weights()
    W.append(w)
    B.append(b)
    
print('Y(tensorflow) \n', X.numpy())
    
# forward propagation (manual)
for layer_idx in range(len(n_neurons)):
    w, b = W[layer_idx], B[layer_idx]
    
    X_cp = matmul(X_cp, w) + b
    X_cp = 1/(1+ exp(-X_cp))
print('Y(manual) : \n', X_cp.numpy())

Input :  (4, 10)
Y(tensorflow) 
 [[0.7111392  0.18692735 0.7255024  0.5854922  0.4544989 ]
 [0.70149904 0.20888393 0.7072701  0.56515443 0.46334806]
 [0.7224216  0.18283015 0.7312375  0.57106686 0.46023956]
 [0.7127534  0.19622679 0.7193955  0.56708086 0.4614766 ]]
Y(manual) : 
 [[0.7111392  0.18692735 0.7255024  0.5854922  0.4544989 ]
 [0.70149904 0.20888393 0.7072701  0.56515443 0.46334806]
 [0.7224216  0.18283015 0.7312375  0.57106686 0.46023956]
 [0.7127534  0.19622679 0.7193955  0.56708086 0.4614766 ]]


## Model Implementation

### Model Implementation with Sequential Method

In [2]:
from tensorflow.keras.layers import Dense

from tensorflow.keras.models import Sequential

n_neurons = [3, 4, 5, 6]

# for n_neuron in n_neurons: 
#     model.append(Dense(units=n_neuron, activation='sigmoid'))
    
    
model = Sequential() # 시퀀셜 객체를 생성
# for n_neuron in n_neurons:
#     model.add(Dense(units=n_neuron, activation='sigmoid'))
    
model.add(Dense(units=10, activation='sigmoid'))
model.add(Dense(units=20, activation='sigmoid'))

### Model IMplementation with Model-subclassing

In [3]:
from tensorflow.keras.layers import Dense

from tensorflow.keras.models import Model

class TestModel(Model):
    def __init__(self):
        super(TestModel, self).__init__()
        
        self.dense1 = Dense(units=10, activation='sigmoid')
        self.dense2 = Dense(units=20, activation='sigmoid')
        
model = TestModel()
print(model.dense1)
print(model.dense2)

### Forward Propagation of Models

In [6]:
import tensorflow as tf
import numpy as np
from tensorflow.keras.layers import Dense

from tensorflow.keras.models import Sequential
from tensorflow.keras.models import Model

X = tf.random.normal(shape=(4, 10))

# Sequential metod
model = Sequential()
model.add(Dense(units=10, activation='sigmoid'))
model.add(Dense(units=20, activation='sigmoid'))

Y = model(X)
print(Y.numpy())

# Model subclassing
class TestModel(Model):
    def __init__(self):
        super(TestModel, self).__init__()
        
        self.dense1 = Dense(units=10, activation='sigmoid')
        self.dense2 = Dense(units=20, activation='sigmoid')
        
    def call(self, x):
        x = self.dense1(x)
        x = self.dense2(x)
        return x
        
model = TestModel()
Y = model(X)

[[0.4222349  0.59802604 0.70591474 0.26297423 0.5609795  0.28619602
  0.37357855 0.413537   0.6322221  0.5845918  0.55440706 0.44011086
  0.6174386  0.6826639  0.46700066 0.60463977 0.5505445  0.35942158
  0.49734825 0.59846157]
 [0.53549916 0.6252327  0.64202577 0.38557547 0.56846017 0.28256425
  0.4137071  0.40379074 0.4806813  0.5670919  0.43670106 0.512021
  0.64955246 0.5873596  0.5217614  0.649315   0.4188103  0.45163932
  0.45049095 0.5174922 ]
 [0.41281155 0.6722065  0.6568531  0.28540704 0.51970243 0.26806292
  0.42491537 0.32778376 0.68055624 0.6144816  0.607117   0.4043333
  0.6078223  0.68393075 0.38079387 0.6517763  0.46936613 0.41149315
  0.53809756 0.54037565]
 [0.43273857 0.534593   0.64956474 0.31709668 0.6191085  0.3166726
  0.38207528 0.40975338 0.50119764 0.55259377 0.5048209  0.5156996
  0.6317705  0.66760087 0.53466463 0.5935897  0.5264862  0.36508343
  0.42285085 0.505938  ]]


In [ ]:
class TestModel(Model):
    def __init__(self, n_neurons):
        super(TestModel, self).__init__()
        self.n_neurons = n_neurons
        
        self.dense_layers = []
        for n_neuron in n_neurons:
             self.dense_layers.append(Dense(units=n_neuron, activation='sigmoid'))
        
    def call(self, x):
        for dense in self.dense_layers:
            x = dense(x)
        return x
    
n_neurons = [3, 4, 5]
model = TestModel(n_neurons)

### Layers in Models

In [5]:
import tensorflow as tf

from tensorflow.keras.layers import Dense
from tensorflow.keras.models import Sequential

X = tf.random.normal(shape=(4, 10))

model = Sequential()
model.add(Dense(units=10, activation='sigmoid'))
model.add(Dense(units=20, activation='sigmoid'))

Y = model(X)

print(type(model.layers)) # model.layers는 list 타입이다.
print(model.layers) # list안에 2개의 dense layer가 들어가있다.

dense1 = model.layers[0]

# for tmp in dir(dense1):
#     print(tmp)

for layer in model.layers:
    w, b = layer.get_weights()
    print(w.shape, b.shape)

<class 'list'>
[<tensorflow.python.keras.layers.core.Dense object at 0x000001BBA0319B20>, <tensorflow.python.keras.layers.core.Dense object at 0x000001BBA68AAF70>]
(10, 10) (10,)
(10, 20) (20,)


### Trainable Variables in Models

In [8]:
import tensorflow as tf

from tensorflow.keras.layers import Dense
from tensorflow.keras.models import Sequential

X = tf.random.normal(shape=(4, 10))

model = Sequential()
model.add(Dense(units=10, activation='sigmoid'))
model.add(Dense(units=20, activation='sigmoid'))

Y = model(X)

print(type(model.trainable_variables))

print(len(model.trainable_variables))

for train_var in model.trainable_variables: # weight와 bias들, 또한 list라서 인덱스로 접근 가능하다.
    print(type(train_var))
    print(train_var.shape)

<class 'list'>
4
<class 'tensorflow.python.ops.resource_variable_ops.ResourceVariable'>
(10, 10)
<class 'tensorflow.python.ops.resource_variable_ops.ResourceVariable'>
(10,)
<class 'tensorflow.python.ops.resource_variable_ops.ResourceVariable'>
(10, 20)
<class 'tensorflow.python.ops.resource_variable_ops.ResourceVariable'>
(20,)
