# 분류 모델 성능 평가 지표
- 정확도(Accuracy)
- 오차행렬(confusion matrix)
- 정밀도(precision)
- 재현율(recall)
- F1 스코어 (정밀도, 재현율의 균형)
- ROC AUC (이진분류일때 잘 쓰임)

# 1. 정확도

$\Large 정확도 = \frac{예측 결과가 동일한 데이터 건수}{전체 예측 데이터 건수} $


- 정확도는 직관적으로 모델 예측 성능을 나타내는 평가 지표
- 이진분류의 경우 데이터의 구성에 따라 ML 모델의 성능을 왜곡할 수 있기 때문에 정확도 수치 하나만 가지고 성능 평가를 하지는 않는다.
- 특히, 불균형 레이블 데이터 분포에서 ML 모델의 성능을 판단한 경우, 정확도는 적합한 평가 지표가 아니다.

# 2. 오차행렬

![IMG_1215](https://user-images.githubusercontent.com/76948864/150466748-563b75c6-1310-41ce-8881-10e11ac12810.jpg)![IMG_1215.jpg]()

# 텐서플로우 사용법

## 1. 텐서만들기와 텐서를 넘파이 배열로 만들기

In [1]:
import tensorflow as tf
import numpy as np

In [2]:
np.set_printoptions(precision=3)

In [3]:
a = np.array([1,2,3], dtype=np.int32)
b = [4,5,6]

### ndarray a와 list b를 텐서로 변환

In [4]:
t_a = tf.convert_to_tensor(a)
t_b = tf.convert_to_tensor(b)

In [5]:
print(t_a)
print(t_b)

tf.Tensor([1 2 3], shape=(3,), dtype=int32)
tf.Tensor([4 5 6], shape=(3,), dtype=int32)


### 영핼렬을 텐서로 만들어보자

In [6]:
t_ones = tf.ones((2,3))
print(t_ones.shape)
print(t_ones)

(2, 3)
tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]], shape=(2, 3), dtype=float32)


### 텐서를 넘파이 배열로 바꾸려면?

In [8]:
ones = t_ones.numpy()

In [10]:
print(type(ones))

<class 'numpy.ndarray'>


### 상수값을 가진 텐서를 만들어보자

In [11]:
const_tensor = tf.constant([1.2, 5, np.pi, np.exp(2)], dtype=tf.float32)
print(const_tensor)

tf.Tensor([1.2   5.    3.142 7.389], shape=(4,), dtype=float32)


### tf.fill()
큰 사이즈의 텐서를 만들 때는 tf.fill이 tf.ones보다 효율적이다

In [12]:
# 첫번째 매개변수는 텐서의 크기(튜플)
# 두번째 매개변수는 전달 값
t_fill = tf.fill((2,3), 3)
print(t_fill)

tf.Tensor(
[[3 3 3]
 [3 3 3]], shape=(2, 3), dtype=int32)


### tf.one_hot()
원-핫 인코딩 행렬을 만들어주는 함수

In [15]:
# 첫번째 매개변수는 원-핫 인코딩 위치 인덱스
# 두번째 매개변수는 원-핫 인코딩 벡터의 길이 전달
tf.one_hot([0,1,3,2], 4)
# 행렬의 크기는 첫번째 매개변수의 길이 x 두번째 매개변수의 크기)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 1.],
       [0., 0., 1., 0.]], dtype=float32)>

## 텐서의 데이터 타입과 크기 조작

실제 모델(CNN)을 만들고 데이터를 처리할 때 입력 텐서의 크기가 안맞으면 실행이 안된다. 이를 처리하려면 텐서를 조작하는 방법을 알아야한다. 어떻게 조정해야 할까?\
cast, reshape, transpose, squeeze

### tf.cast() : 텐서의 데이터 타입의 변경

In [16]:
# int32 -> int64로 변경해보자
t_a_new = tf.cast(t_a, tf.int64)
print(t_a_new)

tf.Tensor([1 2 3], shape=(3,), dtype=int64)


### 텐서 차원 조작

#### 1. 텐서 전치

In [17]:
t = tf.random.uniform(shape=(3,5))
t_tr = tf.transpose(t)
print(t.shape, '------>', t_tr.shape)

(3, 5) ------> (5, 3)


#### 2. 텐서 크기 바꾸기

In [19]:
t = tf.zeros((30,))
t_reshape = tf.reshape(t, shape=(5,6))
print(t_reshape, t_reshape.shape)

tf.Tensor(
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]], shape=(5, 6), dtype=float32) (5, 6)


In [21]:
t = tf.fill((3,5), 9)
print(t)
print('\n')
t_reshape = tf.reshape(t, shape=(-1)) # -1을 넣으면 Flatten해주는 효과가... NxM 차원의 벡터가 생성됨
print(t_reshape)

tf.Tensor(
[[9 9 9 9 9]
 [9 9 9 9 9]
 [9 9 9 9 9]], shape=(3, 5), dtype=int32)


tf.Tensor([9 9 9 9 9 9 9 9 9 9 9 9 9 9 9], shape=(15,), dtype=int32)


#### 3. 불필요한 차원 삭제하기(크기가 1인 차원은 필요없다!)

In [22]:
t = tf.zeros((1,2,1,4,1))
t_sqz = tf.squeeze(t, axis=(2,4))
print(t.shape, '---->', t_sqz.shape)

(1, 2, 1, 4, 1) ----> (1, 2, 4)


## 텐서와 선형대수 연산

In [23]:
tf.random.set_seed(1)
t1 = tf.random.uniform(shape=(5,2), minval=-1.0, maxval=1.0)
t2 = tf.random.normal(shape=(5,2), mean=0.0, stddev=1.0)

In [24]:
print(t1, t2)

tf.Tensor(
[[-0.67   0.803]
 [ 0.262 -0.131]
 [-0.416  0.285]
 [ 0.952 -0.13 ]
 [ 0.32   0.21 ]], shape=(5, 2), dtype=float32) tf.Tensor(
[[ 0.403 -1.088]
 [-0.063  1.337]
 [ 0.712 -0.489]
 [-0.764 -1.037]
 [-1.252  0.021]], shape=(5, 2), dtype=float32)


### 아다마르 곱 (Hadamard product)
같은 크기의 행렬(텐서)를 같은 위치의 element끼리 곱한것

In [25]:
t3 = tf.multiply(t1, t2).numpy()
print(t3)

[[-0.27  -0.874]
 [-0.017 -0.175]
 [-0.296 -0.139]
 [-0.727  0.135]
 [-0.401  0.004]]


### 특정 축을 따라 평균, 합, 표준편차 계산

In [28]:
t4 = tf.math.reduce_mean(t1, axis=0) # axis=0 : column wise
print('컬럼별 평균은 : ', t4)

t4 = tf.math.reduce_sum(t1, axis=0)
print('컬럼별 합은 : ', t4)

t4 = tf.math.reduce_std(t1, axis=0)
print('컬럼별 표준편차는 : ', t4)

컬럼별 평균은 :  tf.Tensor([0.09  0.207], shape=(2,), dtype=float32)
컬럼별 합은 :  tf.Tensor([0.448 1.037], shape=(2,), dtype=float32)
컬럼별 표준편차는 :  tf.Tensor([0.576 0.343], shape=(2,), dtype=float32)


### 일반적인 행렬의 곱(dot product)

In [34]:
t5 = tf.linalg.matmul(t1, t2, transpose_b=True) # transpose a, b : 첫번째냐 두번째냐 어딜 전치해줄지 설정, 이값 안주면 계산이 안됌
print(t5)

tf.Tensor(
[[-1.144  1.115 -0.87  -0.321  0.856]
 [ 0.248 -0.191  0.25  -0.064 -0.331]
 [-0.478  0.407 -0.436  0.022  0.527]
 [ 0.525 -0.234  0.741 -0.593 -1.194]
 [-0.099  0.26   0.125 -0.462 -0.396]], shape=(5, 5), dtype=float32)


### norm 구하기

In [35]:
norm_t1 = tf.norm(t1, ord=2, axis=1).numpy() # ord=2면 프로베니우스 놈
print(norm_t1)

[1.046 0.293 0.504 0.96  0.383]


## 텐서플로우 넘파이 사용 tf.experimental.numpy
텐서플로우 내에서 numpy API를 지원한다

In [39]:
import tensorflow.experimental.numpy as tnp

In [40]:
tnp.array([1,2,3,4])

<tf.Tensor: shape=(4,), dtype=int64, numpy=array([1, 2, 3, 4])>

In [41]:
tnp.array([1,2,3,4]).numpy()

array([1, 2, 3, 4])

https://www.tensorflow.org/api_docs/python/tf/math

https://www.tensorflow.org/api_docs/python/tf/linalg

## 텐서 나누기

### split, stack, concat

#### split

In [42]:
tf.random.set_seed(1)
t = tf.random.uniform((6,))

print(t.numpy())


[0.165 0.901 0.631 0.435 0.292 0.643]


In [44]:
t_splits = tf.split(t, num_or_size_splits=3) # num_or_size_splits : 나눌 개수 , 나눌 크기(서로 다르게 지정가능)
[item.numpy() for item in t_splits]

[array([0.165, 0.901], dtype=float32),
 array([0.631, 0.435], dtype=float32),
 array([0.292, 0.643], dtype=float32)]

In [45]:
t = tf.random.uniform((5,))
print(t.numpy())
t_splits = tf.split(t, num_or_size_splits=[3,2]) # 3개, 2개 리스트로 전달한다
t_splits

[0.51  0.444 0.409 0.992 0.689]


[<tf.Tensor: shape=(3,), dtype=float32, numpy=array([0.51 , 0.444, 0.409], dtype=float32)>,
 <tf.Tensor: shape=(2,), dtype=float32, numpy=array([0.992, 0.689], dtype=float32)>]

In [46]:
[item.numpy() for item in t_splits]

[array([0.51 , 0.444, 0.409], dtype=float32),
 array([0.992, 0.689], dtype=float32)]

#### stack
쌓을 때 크기가 같다

In [51]:
A = tf.ones((3,))
B = tf.zeros((3,))
S = tf.stack([A, B], axis=0)
print(S.numpy())
S = tf.stack([A, B], axis=1)
print(S.numpy())

[[1. 1. 1.]
 [0. 0. 0.]]
[[1. 0.]
 [1. 0.]
 [1. 0.]]


#### concat
그냥 붙여

In [52]:
A = tf.ones((3,))
B = tf.zeros((2,))
C = tf.concat([A,B], axis=0)
print(C.numpy())

[1. 1. 1. 0. 0.]


In [55]:
C = tf.concat([A, B], axis=1) # 차원이 다르면... axis설정에 따라 연산이 안된다... null은 처리가 안된다...
print(C.numpy())

InvalidArgumentError: ignored

# 메모
아니 진짜 axis너무 헷갈림 -> 진짜 이해될때까지 정리하자