In [1]:
import numpy as np

# 넘파이 stack vs concatenate

넘파이 객체를 합칠 때 사용하는 메소드
- stack : 두 array를 합치나 각자의 차원이 남아 차원을 유지한다.
- concatenate : 단순히 합쳐서 이어 붙이는 함수, 차원 유지x

In [2]:
a = np.array([[1,2], [3,4]])
b = np.array([[5,6], [7,8]])
c = np.array([[5,6], [7,8], [9,10]])

In [18]:
c

array([[ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [6]:
print(np.concatenate((a,b), axis=0), '\n\n', np.concatenate((a,b), axis=0).shape)

[[1 2]
 [3 4]
 [5 6]
 [7 8]] 

 (4, 2)


In [8]:
print(np.concatenate((a,b), axis=1), '\n\n', np.concatenate((a,b), axis=1).shape)

[[1 2 5 6]
 [3 4 7 8]] 

 (2, 4)


In [9]:
print(np.stack((a,b), axis=0), '\n\n', np.stack((a,b), axis=0).shape)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]] 

 (2, 2, 2)


In [10]:
print(np.stack((a,b), axis=1), '\n\n', np.stack((a,b), axis=1).shape)

[[[1 2]
  [5 6]]

 [[3 4]
  [7 8]]] 

 (2, 2, 2)


## 차원이 다를 때

In [14]:
# 2by2와 2by3 를 axis=0으로 이을 때는 가능
print(np.concatenate((a,c), axis=0), '\n\n',np.concatenate((a,c), axis=0).shape)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]] 

 (5, 2)


In [15]:
# 2by2와 2by3를 axis=1로 하려니 2와 3이 차원이 달라 불가
print(np.concatenate((a,c), axis=1), '\n\n',np.concatenate((a,c), axis=1).shape)

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 3

In [16]:
# 차원을 유지한채 붙이려 하니 서로 차원이 달라 불가
print(np.stack((a,c), axis=0), '\n\n', np.stack((a,c), axis=0).shape)

ValueError: all input arrays must have the same shape

In [17]:
# 차원을 유지한채 붙이려 하니 서로 차원이 달라 불가
print(np.stack((a,c), axis=1), '\n\n', np.stack((a,c), axis=1).shape)

ValueError: all input arrays must have the same shape