In [1]:
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt

In [18]:
np.set_printoptions(precision=3)

# 텐서 생성 및 사용법

## Tensor

### 1. 스칼라(Scalar)
- 랭크(rank)-0 텐서

#### 스칼라 텐서 생성

In [3]:
a = tf.constant(1)
b = tf.constant(2)
print("a : ", a)
print('b : ', b)

a :  tf.Tensor(1, shape=(), dtype=int32)
b :  tf.Tensor(2, shape=(), dtype=int32)


#### 랭크 확인

In [4]:
print(tf.rank(a))

tf.Tensor(0, shape=(), dtype=int32)


#### 자료형 캐스팅

In [10]:
a = tf.cast(a, tf.float32)
b = tf.cast(b, tf.float32)
print(a.dtype)
print(b.dtype)

<dtype: 'float32'>
<dtype: 'float32'>


#### [tip] float32
텐서플로우는 딥러닝 연산시 float32를 숫자형 데이터를 나타내는 기본 자료형으로 사용한다.

In [8]:
# tensorflow data dtypes
print(dir(tf.dtypes))

['DType', 'QUANTIZED_DTYPES', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '_sys', 'as_dtype', 'bfloat16', 'bool', 'cast', 'complex', 'complex128', 'complex64', 'double', 'float16', 'float32', 'float64', 'half', 'int16', 'int32', 'int64', 'int8', 'qint16', 'qint32', 'qint8', 'quint16', 'quint8', 'resource', 'saturate_cast', 'string', 'uint16', 'uint32', 'uint64', 'uint8', 'variant']


#### 연산
tf.math docs https://www.tensorflow.org/api_docs/python/tf/math \
tf.linalg docs https://www.tensorflow.org/api_docs/python/tf/linalg

In [11]:
# 덧셈
c = tf.math.add(a,b)
print('result : ', c)
print('rank : ', tf.rank(c))

result :  tf.Tensor(3.0, shape=(), dtype=float32)
rank :  tf.Tensor(0, shape=(), dtype=int32)


In [12]:
# 뺄셈
print(tf.math.subtract(a,b))

tf.Tensor(-1.0, shape=(), dtype=float32)


In [13]:
# 곱셈
print(tf.math.multiply(a,b))

tf.Tensor(2.0, shape=(), dtype=float32)


In [14]:
# 나눗셈
print(tf.math.divide(a,b))

tf.Tensor(0.5, shape=(), dtype=float32)


In [15]:
# 나머지
print(tf.math.mod(a,b))

tf.Tensor(1.0, shape=(), dtype=float32)


In [17]:
# 몫
print(tf.math.floordiv(a,b))

tf.Tensor(0.0, shape=(), dtype=float32)


### 2. 벡터(Vector)
- rank-1 텐서

In [19]:
ls = [10., 20., 30.] # float
arr = np.array([10., 20., 30.])

#### 벡터 텐서 생성 

In [29]:
# tf.constant를 이용해 생성
vec1 = tf.constant(ls, dtype=tf.float32)
vec2 = tf.constant(arr, dtype=tf.float32) 
# 타입지정 안해주니까 float64로 들어간다.
# arr의 기본타입이 float64 -> 넘파이 배열타입을 따라가나보다.

print('vec1 : ', vec1)
print('vec2 : ', vec2)

vec1 :  tf.Tensor([10. 20. 30.], shape=(3,), dtype=float32)
vec2 :  tf.Tensor([10. 20. 30.], shape=(3,), dtype=float32)


In [31]:
# tf.convert_to_tensor를 이용해 생성
vec3 = tf.convert_to_tensor(ls, dtype=tf.float32)
vec4 = tf.convert_to_tensor(arr, dtype=tf.float32)
print('vec3 : ', vec3)
print('vec4 : ', vec4)

vec3 :  tf.Tensor([10. 20. 30.], shape=(3,), dtype=float32)
vec4 :  tf.Tensor([10. 20. 30.], shape=(3,), dtype=float32)


#### 랭크 확인

In [32]:
print(tf.rank(vec1))
print(tf.rank(vec2))
print(tf.rank(vec3))
print(tf.rank(vec4))

tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)


#### 연산
element-wise 계산

In [34]:
# 덧셈1
add1 = tf.math.add(vec1, vec2)
print('result : ', add1)
print('rank : ', tf.rank(add1))

result :  tf.Tensor([20. 40. 60.], shape=(3,), dtype=float32)
rank :  tf.Tensor(1, shape=(), dtype=int32)


In [35]:
# 덧셈2 : 파이썬의 연산자를 사용해도 된다.
add2 = vec1 + vec2
print('result : ', add2)
print('rank : ', tf.rank(add2))

result :  tf.Tensor([20. 40. 60.], shape=(3,), dtype=float32)
rank :  tf.Tensor(1, shape=(), dtype=int32)


In [36]:
# 사칙연산1
print(tf.math.subtract(vec1, vec2))
print(tf.math.multiply(vec1, vec2))
print(tf.math.divide(vec1, vec2))
print(tf.math.mod(vec1, vec2))
print(tf.math.floordiv(vec1, vec2))

tf.Tensor([0. 0. 0.], shape=(3,), dtype=float32)
tf.Tensor([100. 400. 900.], shape=(3,), dtype=float32)
tf.Tensor([1. 1. 1.], shape=(3,), dtype=float32)
tf.Tensor([0. 0. 0.], shape=(3,), dtype=float32)
tf.Tensor([1. 1. 1.], shape=(3,), dtype=float32)


In [37]:
# 사칙연산2
print(vec1 - vec2)
print(vec1 * vec2)
print(vec1 / vec2)
print(vec1 % vec2)
print(vec1 // vec2)

tf.Tensor([0. 0. 0.], shape=(3,), dtype=float32)
tf.Tensor([100. 400. 900.], shape=(3,), dtype=float32)
tf.Tensor([1. 1. 1.], shape=(3,), dtype=float32)
tf.Tensor([0. 0. 0.], shape=(3,), dtype=float32)
tf.Tensor([1. 1. 1.], shape=(3,), dtype=float32)


In [38]:
# 합계 구하기 - reduce_sum()
print(tf.reduce_sum(vec1))
print(tf.reduce_sum(vec2))

tf.Tensor(60.0, shape=(), dtype=float32)
tf.Tensor(60.0, shape=(), dtype=float32)


In [39]:
# 거듭제곱1 - tf.math.square()
print(tf.math.square(vec1))

tf.Tensor([100. 400. 900.], shape=(3,), dtype=float32)


In [40]:
# 거듭제곱2 - **
print(vec1**2)

tf.Tensor([100. 400. 900.], shape=(3,), dtype=float32)


In [41]:
# 제곱근1 - tf.math.sqrt
print(tf.math.sqrt(vec1))

tf.Tensor([3.162 4.472 5.477], shape=(3,), dtype=float32)


In [42]:
# 제곱근2 - **0.5
print(vec1**0.5)

tf.Tensor([3.162 4.472 5.477], shape=(3,), dtype=float32)


In [43]:
# broadcasting
print(vec1 + 10)

tf.Tensor([20. 30. 40.], shape=(3,), dtype=float32)


### 3. 행렬(Matrix)
- rank-2 텐서

#### 행렬 텐서 생성

In [46]:
# 2차원 배열 정의
ls2 = [[10, 20], [30,40]]
print(ls2)

[[10, 20], [30, 40]]


In [48]:
mat1 = tf.constant(ls2)
mat2 = tf.convert_to_tensor(ls2)
print('mat1 :', mat1)
print(tf.rank(mat1), '\n')
print('mat2 : ',mat2)
print(tf.rank(mat2))

mat1 : tf.Tensor(
[[10 20]
 [30 40]], shape=(2, 2), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32) 

mat2 :  tf.Tensor(
[[10 20]
 [30 40]], shape=(2, 2), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)


#### 벡터를 이용해 행렬 만들기
벡터를 쌓거나 붙여서 행렬을 만들 수 있다.

In [52]:
vec1 = tf.constant([1, 0])
vec2 = tf.constant([-1, 2])

# 위 아래로 쌓기 - stack
mat3 = tf.stack([vec1, vec2])
print(mat3)

tf.Tensor(
[[ 1  0]
 [-1  2]], shape=(2, 2), dtype=int32)


In [53]:
# vec1를 열벡터로 해서 2개를 붙이는 것
print(tf.stack([vec1, vec2], axis=1))

tf.Tensor(
[[ 1 -1]
 [ 0  2]], shape=(2, 2), dtype=int32)


#### 연산
기본 연산은 다 element-wise

In [55]:
# 요소 곱
mul = tf.math.multiply(mat1, mat3)
print('result : ', mul)
print('rank : ', tf.rank(mul))

result :  tf.Tensor(
[[ 10   0]
 [-30  80]], shape=(2, 2), dtype=int32)
rank :  tf.Tensor(2, shape=(), dtype=int32)


In [56]:
# 일반 행렬 곱
mat_mul = tf.matmul(mat1, mat3)
print('result : ', mat_mul)
print('rank : ', tf.rank(mat_mul))

result :  tf.Tensor(
[[-10  40]
 [-10  80]], shape=(2, 2), dtype=int32)
rank :  tf.Tensor(2, shape=(), dtype=int32)


In [58]:
# broadcasting
bc = tf.math.multiply(mat1, 3)
print('result : ', bc)
print('rank : ', tf.rank(bc))

result :  tf.Tensor(
[[ 30  60]
 [ 90 120]], shape=(2, 2), dtype=int32)
rank :  tf.Tensor(2, shape=(), dtype=int32)


In [59]:
# 덧셈1
add1 = tf.math.add(mat1, mat3)
print(add1)
print(tf.rank(add1))

tf.Tensor(
[[11 20]
 [29 42]], shape=(2, 2), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)


In [60]:
# 덧셈2
add2 = mat1 + mat3
print(add2)
print(tf.rank(add2))

tf.Tensor(
[[11 20]
 [29 42]], shape=(2, 2), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)


#### 텐서를 넘파이로 바꾸기
Tensor.numpy()를 쓰면된다.

In [61]:
np_arr = mat1.numpy()
print(type(np_arr))
print(np_arr)

<class 'numpy.ndarray'>
[[10 20]
 [30 40]]


#### 특수 행렬 생성
tf.ones(), tf.zeros(), tf.fill()

In [66]:
# 일행렬 만들기
t_ones = tf.ones((2,3))
print(t_ones.shape)
print(t_ones)

(2, 3)
tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]], shape=(2, 3), dtype=float32)


In [67]:
# 영행렬 만들기
t_zeros = tf.zeros((2,3))
print(t_zeros.shape)
print(t_zeros)

(2, 3)
tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]], shape=(2, 3), dtype=float32)


In [68]:
# tf.fill()
# 큰 사이즈의 텐서를 만들 때는 tf.fill이 tf.ones보다 효율적이다

t_fill = tf.fill((2,3), 7)
print(t_fill)

tf.Tensor(
[[7 7 7]
 [7 7 7]], shape=(2, 3), dtype=int32)


In [69]:
# 원-핫 인코딩 행렬
# tf.one_hot()

# 첫번째 매개변수는 원-핫 인코딩 위치 인덱스
# 두번째 매개변수는 원-핫 인코딩 벡터의 길이 전달
tf.one_hot([0,1,3,2], 4)
# 행렬의 크기는 첫번째 매개변수의 길이 x 두번째 매개변수의 크기)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 1.],
       [0., 0., 1., 0.]], dtype=float32)>

### 4. 고차원 텐서(Tensor)
rank-3 텐서

#### 텐서 생성

In [64]:
# 2차원 배열 정의
mat1 = [[1,2,3,4], [5,6,7,8]]
mat2 = [[9,10,11,12], [13,14,15,16]]
mat3 = [[17,18,19,20], [21,22,23,24]]

tensor1 = tf.constant([mat1, mat2, mat3])

print('rank : ', tf.rank(tensor1))

print('tensor1 : ', tensor1)
# shape=(3,2,4)에서 앞에 3이 channel개념

rank :  tf.Tensor(3, shape=(), dtype=int32)
tensor1 :  tf.Tensor(
[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]

 [[17 18 19 20]
  [21 22 23 24]]], shape=(3, 2, 4), dtype=int32)


#### stack으로 쌓아 만들기

In [65]:
tensor2 = tf.stack([mat1, mat2, mat3])
print('rank : ', tf.rank(tensor2))
print('tensor2 : ', tensor2)

rank :  tf.Tensor(3, shape=(), dtype=int32)
tensor2 :  tf.Tensor(
[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]

 [[17 18 19 20]
  [21 22 23 24]]], shape=(3, 2, 4), dtype=int32)


### 5. 텐서의 인덱싱, 슬라이싱
텐서도 파이썬 리스트, 넘파이 배열의 인덱싱, 슬라이싱과 방법이 비슷하다.

벡터

In [70]:
vec = tf.constant([10, 20, 30, 40, 50])
print(vec)

tf.Tensor([10 20 30 40 50], shape=(5,), dtype=int32)


In [71]:
print(vec[0])

tf.Tensor(10, shape=(), dtype=int32)


In [72]:
print(vec[-1])

tf.Tensor(50, shape=(), dtype=int32)


In [73]:
print(vec[:3])

tf.Tensor([10 20 30], shape=(3,), dtype=int32)


행렬

In [75]:
mat = tf.constant([[1,2,3,4], [5,6,7,8]])
print(mat)

tf.Tensor(
[[1 2 3 4]
 [5 6 7 8]], shape=(2, 4), dtype=int32)


In [76]:
print(mat[0,2])

tf.Tensor(3, shape=(), dtype=int32)


In [77]:
print(mat[0, :])

tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)


In [78]:
print(mat[:, 1])

tf.Tensor([2 6], shape=(2,), dtype=int32)


텐서

In [79]:
tensor = tf.constant([
    [[1,2,3],
     [4,5,6]],
    [[7,8,9],
     [10, 11, 12]]
])
print(tensor)

tf.Tensor(
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]], shape=(2, 2, 3), dtype=int32)


In [80]:
print(tensor[0, :, :])

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


In [81]:
print(tensor[:, :2, :2])

tf.Tensor(
[[[ 1  2]
  [ 4  5]]

 [[ 7  8]
  [10 11]]], shape=(2, 2, 2), dtype=int32)


### 6. 텐서의 차원 조작
실제 모델(예 : CNN)을 만들고 데이터를 모델에 넣어야할 때 데이터의 텐서 크기가 안맞으면 실행 자체가 불가하다. 이를 피하기 위해 차원이 다를 경우 맞춰서 넣어줘야 한다.
- reshape
- transpose
- squeeze
- split

#### transpose

In [89]:
mat = tf.constant(tf.fill((3,6), 4))
print(mat)

tf.Tensor(
[[4 4 4 4 4 4]
 [4 4 4 4 4 4]
 [4 4 4 4 4 4]], shape=(3, 6), dtype=int32)


In [90]:
# 전치1
mat_tr = tf.transpose(mat)
print(mat_tr)

tf.Tensor(
[[4 4 4]
 [4 4 4]
 [4 4 4]
 [4 4 4]
 [4 4 4]
 [4 4 4]], shape=(6, 3), dtype=int32)


In [91]:
# 전치2
print(mat.numpy().T)
print(np.transpose(mat))

[[4 4 4]
 [4 4 4]
 [4 4 4]
 [4 4 4]
 [4 4 4]
 [4 4 4]]
[[4 4 4]
 [4 4 4]
 [4 4 4]
 [4 4 4]
 [4 4 4]
 [4 4 4]]


#### reshape

In [94]:
# 고차원 텐서로도 변경가능
mat_reshape = tf.reshape(mat, shape=(2,3,3)) 
print(mat_reshape)

tf.Tensor(
[[[4 4 4]
  [4 4 4]
  [4 4 4]]

 [[4 4 4]
  [4 4 4]
  [4 4 4]]], shape=(2, 3, 3), dtype=int32)


In [95]:
mat_reshape = tf.reshape(mat, shape=(9,2))
print(mat_reshape)

tf.Tensor(
[[4 4]
 [4 4]
 [4 4]
 [4 4]
 [4 4]
 [4 4]
 [4 4]
 [4 4]
 [4 4]], shape=(9, 2), dtype=int32)


In [96]:
# -1을 넣으면 벡터로 바꿔준다.
mat_reshape = tf.reshape(mat, shape=(-1))
print(mat_reshape)
print(mat_reshape.shape)

tf.Tensor([4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4], shape=(18,), dtype=int32)
(18,)


#### squeeze
불필요한 차원을 없애준다. (차원 크기가 1짜리인 것은 필요없다)

In [97]:
# 1,2,1,4,1 차원의 영행렬 생성
t = tf.zeros((1,2,1,4,1)) # 2,4인덱스를 삭제
t_sqz = tf.squeeze(t, axis=(2,4))
print(t.shape, '-----------', t_sqz.shape)

(1, 2, 1, 4, 1) ----------- (1, 2, 4)


#### split
- 텐서를 쪼갤 수 있다.

In [133]:
tf.random.set_seed(1)
t = tf.random.uniform((6,))

print(t.numpy())

[0.165 0.901 0.631 0.435 0.292 0.643]


In [134]:
t_splits = tf.split(t, num_or_size_splits=3) # num_or_size_splits : 나눌 개수 , 나눌 크기(서로 다르게 지정가능)
[item.numpy() for item in t_splits]

[array([0.165, 0.901], dtype=float32),
 array([0.631, 0.435], dtype=float32),
 array([0.292, 0.643], dtype=float32)]

In [135]:
t = tf.random.uniform((5,))
print(t.numpy())
t_splits = tf.split(t, num_or_size_splits=[3,2]) # 3개, 2개 리스트로 전달한다
t_splits

[0.51  0.444 0.409 0.992 0.689]


[<tf.Tensor: shape=(3,), dtype=float32, numpy=array([0.51 , 0.444, 0.409], dtype=float32)>,
 <tf.Tensor: shape=(2,), dtype=float32, numpy=array([0.992, 0.689], dtype=float32)>]

In [136]:
[item.numpy() for item in t_splits]

[array([0.51 , 0.444, 0.409], dtype=float32),
 array([0.992, 0.689], dtype=float32)]

### 7. 변수(variable)
딥러닝 모델을 만들 때 변수를 활용하면 정교하게 연산을 제어할 수 있다.\
특히, 가중치와 학습률(lr)처럼 모델 학습 및 추론 과정에서 값이 변경되는 경우 변수를 활용한다.
- 역전파를 할 때 그래프 구조를 이용해 미분 연산을 하는데, 이 때 중간 연산 결과인 미분계수들을 저장할 때 변수를 이용한다. 업데이트 할 때 마다 변수값이 변한다.
- 최적화 알고리즘을 적용할 때 모델이 학습하는 속도를 정하는 학습률도 변수로 저장된다.

#### 변수생성

In [98]:
tensor = tf.constant([[0,1,2], [3,4,5]])
print(tensor)

tf.Tensor(
[[0 1 2]
 [3 4 5]], shape=(2, 3), dtype=int32)


텐서를 Variable 함수에 넣으면 텐서플로우 변수가 생성된다. 여기서 텐서의 입력값은 변수의 초기값으로 설정된다. 업데이트 시마다 값이 변경될 수 있다.

In [99]:
tensor_var = tf.Variable(tensor)
print(tensor_var)

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[0, 1, 2],
       [3, 4, 5]])>


In [106]:
# 변수 이름도 지정가능하다.
tensor_var = tf.Variable(tensor, name="my_var")
print(tensor_var)

<tf.Variable 'my_var:0' shape=(2, 3) dtype=int32, numpy=
array([[0, 1, 2],
       [3, 4, 5]])>


변수는 텐서 구조에 저장되어 있는 값이 달라질 수 있다는 점에서 값을 변경할 수 없는 상수 형태의 텐서를 만드는 constant 함수와 구별된다.

#### 변수속성
변수의 속성값들을 확인해보자.

In [101]:
print([name for name in dir(tensor_var) if name[0]!='_'])

['SaveSliceInfo', 'aggregation', 'assign', 'assign_add', 'assign_sub', 'batch_scatter_update', 'constraint', 'count_up_to', 'create', 'device', 'dtype', 'eval', 'experimental_ref', 'from_proto', 'gather_nd', 'get_shape', 'graph', 'handle', 'initial_value', 'initialized_value', 'initializer', 'is_initialized', 'load', 'name', 'numpy', 'op', 'read_value', 'ref', 'scatter_add', 'scatter_div', 'scatter_max', 'scatter_min', 'scatter_mul', 'scatter_nd_add', 'scatter_nd_max', 'scatter_nd_min', 'scatter_nd_sub', 'scatter_nd_update', 'scatter_sub', 'scatter_update', 'set_shape', 'shape', 'sparse_read', 'synchronization', 'to_proto', 'trainable', 'value']


In [107]:
print('이름 : ', tensor_var.name)
print('크기 : ', tensor_var.shape)
print('자료형 : ', tensor_var.dtype)
print('배열 : ', tensor_var.numpy())

이름 :  my_var:0
크기 :  (2, 3)
자료형 :  <dtype: 'int32'>
배열 :  [[0 1 2]
 [3 4 5]]


#### 변수변경(값 업데이트)
- assign() 메소드를 이용하면 변수에 새로운 값을 할당할 수 있다. 
- 단, 입력 차원과 데이터 타입이 같아야 한다.

In [108]:
print(tensor_var)
tensor_var.assign([[1,1,1], [2,2,2]])
print(tensor_var)

<tf.Variable 'my_var:0' shape=(2, 3) dtype=int32, numpy=
array([[0, 1, 2],
       [3, 4, 5]])>
<tf.Variable 'my_var:0' shape=(2, 3) dtype=int32, numpy=
array([[1, 1, 1],
       [2, 2, 2]])>


#### 변수를 텐서로 변환
- convert_to_tensor() 함수를 이용하면, 변수를 텐서로 변경할 수 있다.
- 텐서로 변경하면 크기와 값을 변경할 수 없다.

In [109]:
tensor2 = tf.convert_to_tensor(tensor_var)
print(tensor2)

tf.Tensor(
[[1 1 1]
 [2 2 2]], shape=(2, 3), dtype=int32)


텐서플로우 변수도 텐서 연산과 동일하게 연산자 또는 함수를 사용하여 연산할 수 있다.

### 8. 자동미분(autodiff)
- Automatic Differentiation 또는 autodiff

In [113]:
g = tf.random.Generator.from_seed(1)
X = g.normal(shape=(10, ))
y = 3*X - 2
print('X : ', X.numpy())
print('y : ', y.numpy())

X :  [ 0.438 -0.534 -0.077  1.566 -0.101 -0.274  1.42   1.261 -0.436 -1.963]
y :  [-0.685 -3.603 -2.231  2.697 -2.304 -2.823  2.261  1.783 -3.309 -7.89 ]


In [119]:
# MSE 함수 정의
def loss_mse(X, y, a, b):
    y_pred = a*X + b
    squared_error = (y_pred - y) ** 2
    mean_squared_error = tf.reduce_mean(squared_error)
    
    return mean_squared_error

#### tf.GradientTape
- 텐서플로우가 자동 미분하는 중간 과정을 모두 기록할 수 있다.

- a,b를 값이 0.0으로 초기화 해준다.
- 자동미분을 200번 진행하고 20번마다 중간 계산 결과를 출력해보자.

In [132]:
a = tf.Variable(0.0)
b = tf.Variable(0.0)

EPOCHS = 200

for epoch in range(1, EPOCHS+1):
    with tf.GradientTape() as tape:
        mse = loss_mse(X, y, a, b)
    
    grad = tape.gradient(mse, {'a' : a, 'b' : b})
    d_a, d_b = grad['a'], grad['b']
    
    a.assign_sub(d_a * 0.05)
    b.assign_sub(d_b * 0.05)
    
    if epoch % 20 == 0:
        print(f'EPOCH {epoch} - MSE : {mse:.4f} --- a : {a.numpy():.4f} --- b : {b.numpy():.4f}')

EPOCH 20 - MSE : 0.3061 --- a : 2.6068 --- b : -1.6483
EPOCH 40 - MSE : 0.0068 --- a : 2.9455 --- b : -1.9426
EPOCH 60 - MSE : 0.0002 --- a : 2.9922 --- b : -1.9910
EPOCH 80 - MSE : 0.0000 --- a : 2.9988 --- b : -1.9986
EPOCH 100 - MSE : 0.0000 --- a : 2.9998 --- b : -1.9998
EPOCH 120 - MSE : 0.0000 --- a : 3.0000 --- b : -2.0000
EPOCH 140 - MSE : 0.0000 --- a : 3.0000 --- b : -2.0000
EPOCH 160 - MSE : 0.0000 --- a : 3.0000 --- b : -2.0000
EPOCH 180 - MSE : 0.0000 --- a : 3.0000 --- b : -2.0000
EPOCH 200 - MSE : 0.0000 --- a : 3.0000 --- b : -2.0000


$ y = 3x-2$ 에 근사하는 것을 볼 수 있다.

#### tf.random에 대한 팁
텐서플로우는 2개의 난수 생성 프로세스를 제공한다. https://www.tensorflow.org/guide/random_numbers?hl=ko
1. tf.random.Generator 객체 사용해서 생성
2. tf.random.stateless_uniform와 같은 순수-함수형으로 상태가 없는 랜덤 함수를 통한 방식. 같은 디바이스에서 동일한 인수를 (시드값 포함) 통해 해당 함수를 호출 하면 항상 같은 결과를 출력 합니다.
3. tf.random.uniform, tf.random.normal 같은 RNG들. TF 1.x에서 쓰이던 구시대의 유물같은것. 사용을 권장하지 않는다.

## 헷갈리는 것 정리
1. stack은 인자를 []로 받는다
2. 영행렬, 1행렬은 인자를 튜플로 받는다