## Numpy 배열 생성하기
- Numpy는 Numeric python의 줄임말
- 수학분야 관련된 통계 연산 작업시 필요한 라이브러리
- 과학 계산 컴퓨팅과 데이터 분석에 필요한 가장 기본적인 패키지

<br>

- Numpy배열은 리스트와 거의 흡사하지만 연산속도가 빠르고 메모리 효율성이 높아서 대용량 데이터를 다루는데 성능상 우위를 차지한다.
- 사용하기 전에 라이브러리 모듈을 import해야 한다.

1. array() 사용
2. random 랜덤함수 사용

In [1]:
# 모듈 임포트
import numpy as np

### 리스트와 numpy배열을 각각 생성해 두개를 비교해보자.

- numpy배열을 만드는 방법
    1. array()
    2. 랜덤함수
    
<br>

- 리스트는 출력 결과가 [ ] 안에 들어오고 각 요소들이 ,로 구분된다.
- 넘파이배열은 출력 결과가 [ ]안에 들어오고 각 요소들이 그냥 나열된다.

<br>

- 넘파이배열의 타입은 numpy.ndarray 타입으로 나온다.
- ndarray 클래스
    - 다차원 행렬구조를 지원하는 numpy의 핵심 클래스

In [9]:
myList = [4,5,6,7]

myArr = np.array(myList)

print(myList)
print(myArr)

print(type(myList))
print(type(myArr)) # ndarray 기억

[4, 5, 6, 7]
[4 5 6 7]
<class 'list'>
<class 'numpy.ndarray'>


### 슬라이싱과 인덱싱으로 보는 리스트와 np.array의 차이점

In [16]:
# 슬라이싱(숫자일때는 뒷부분 숫자가 포함되지 않는다.)
list_sub = myList[1:3] 
print(list_sub)

arr_sub = myArr[1:3]
print(arr_sub)

# 인덱싱 및 요소 변환
list_sub[0] = -5
arr_sub[0] = -5

print(list_sub)
print(arr_sub)

[5, 6]
[-5  6]
[-5, 6]
[-5  6]


**차이점**
- 리스트는 원본이 안바뀐다. 원본을 copy해서 새로운걸 만든다.
- np배열은 원본이 바뀐다.
- 메모리 활용적인 성능면에서는 np배열이 성능이 좋다.

In [18]:
print(myList)
print(myArr)

[4, 5, 6, 7]
[ 4 -5  6  7]


### 랜덤함수를 이용한 Numpy배열 생성
- random 함수 사용

In [22]:
help(np.random.rand)

Help on built-in function rand:

rand(...) method of numpy.random.mtrand.RandomState instance
    rand(d0, d1, ..., dn)
    
    Random values in a given shape.
    
    .. note::
        This is a convenience function for users porting code from Matlab,
        and wraps `random_sample`. That function takes a
        tuple to specify the size of the output, which is consistent with
        other NumPy functions like `numpy.zeros` and `numpy.ones`.
    
    Create an array of the given shape and populate it with
    random samples from a uniform distribution
    over ``[0, 1)``.
    
    Parameters
    ----------
    d0, d1, ..., dn : int, optional
        The dimensions of the returned array, must be non-negative.
        If no argument is given a single Python float is returned.
    
    Returns
    -------
    out : ndarray, shape ``(d0, d1, ..., dn)``
        Random values.
    
    See Also
    --------
    random
    
    Examples
    --------
    >>> np.random.rand(3,2)
    arra

In [20]:
a = np.random.rand?

Docstring:
rand(d0, d1, ..., dn)

Random values in a given shape.

.. note::
    This is a convenience function for users porting code from Matlab,
    and wraps `random_sample`. That function takes a
    tuple to specify the size of the output, which is consistent with
    other NumPy functions like `numpy.zeros` and `numpy.ones`.

Create an array of the given shape and populate it with
random samples from a uniform distribution
over ``[0, 1)``.

Parameters
----------
d0, d1, ..., dn : int, optional
    The dimensions of the returned array, must be non-negative.
    If no argument is given a single Python float is returned.

Returns
-------
out : ndarray, shape ``(d0, d1, ..., dn)``
    Random values.

See Also
--------
random

Examples
--------
>>> np.random.rand(3,2)
array([[ 0.14022471,  0.96360618],  #random
       [ 0.37601032,  0.25528411],  #random
       [ 0.49313049,  0.94909878]]) #random
Type:      builtin_function_or_method


In [35]:
a = np.random.rand(5)
print(a)
print(type(a))

b = np.random.randint(1,10,5) # 10은 미포함
print(b)
print(type(b))

c = np.random.randn(10) # 가우시안 표준분포 값
print(c)
print(type(c))

[0.80040908 0.67233576 0.38148834 0.37894219 0.64836804]
<class 'numpy.ndarray'>
[8 2 5 2 2]
<class 'numpy.ndarray'>
[-0.01133098  0.18932437  1.03221467 -1.50613544 -1.65360293 -0.8034213
 -2.0275574  -0.68839184  0.89312009  0.97056129]
<class 'numpy.ndarray'>


### np배열 생성과 동시에 초기화
- zeros() : 0으로 초기화
- ones() : 1로 초기화
- arange() : range함수와 유사

In [41]:
# 0으로 초기화
az = np.zeros(10) # size=10짜리 벡터생성, 각 element는 float
print(az)
az.dtype

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


dtype('float64')

In [47]:
# 1로 초기화한 size=10인 배열
ao = np.ones(10)
print(ao)
ao.dtype

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


dtype('float64')

In [46]:
# 브로드캐스팅
ao*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [48]:
# 항등행렬
ae = np.eye(3)
print(ae)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [51]:
# arange 함수
print(np.arange(0,3))
print(np.arange(3))
print(np.arange(3,7))
print(np.arange(3,10,2)) # 2는 step

[0 1 2]
[0 1 2]
[3 4 5 6]
[3 5 7 9]


In [53]:
# full
afull = np.full((5,5),-11)
print(afull)

[[-11 -11 -11 -11 -11]
 [-11 -11 -11 -11 -11]
 [-11 -11 -11 -11 -11]
 [-11 -11 -11 -11 -11]
 [-11 -11 -11 -11 -11]]
