파이토치는 테이프(tape)기반 자동 미분 방식을 구현한다. 이 방식은 계산 그래프를 동적으로 정의하고 실행할 수 있다. 디버깅이 아주 편리하며 복잡한 모델을 손쉽게 만들게 해준다.

# 동적 계산 그래프와 정적 계산 그래프
씨아노, 카페, 텐서플로와 같은 정적 프레임워크는 먼저 계산 그래프를 정의하고 컴파일한 다음 실행해야 한다. 이 방식은 제품 시스템과 모바일 환경에서 매우 효율적이지만 연구나 개발을 할 땐 꽤 번거로울 수 있다.\
체이너, 다이넷, 파이토치같은 최신 프레임워크는 동적 계산 그래프를 구현하여 좀 더 유연한 명령형 스타일의 개발을 지원하며 실행할 때마다 모델을 컴파일하지 않아도 된다. 동적 계산 그래프는 특히 입력마다 다른 그래프 구조가 만들어질 수 있는 NLP 모델링 작업에 잘 맞는다.

# 텐서 만들고 조작하기

## 헬퍼 함수 정의

In [7]:
def describe(x):
    print('타입 : {}'.format(x.type()))
    print('크기 : {}'.format(x.shape))
    print('값 : \n{}'.format(x))

## 텐서
torch.Tensor <-> tf.constant

In [23]:
import torch
describe(torch.Tensor(2,3))

타입 : torch.FloatTensor
크기 : torch.Size([2, 3])
값 : 
tensor([[8.1275e-44, 7.0065e-44, 7.4269e-44],
        [6.4460e-44, 7.2868e-44, 7.4269e-44]])


### Scalar

#### 텐서만들기

In [13]:
sc = torch.Tensor([1.])
describe(sc)

타입 : torch.FloatTensor
크기 : torch.Size([1])
값 : 
tensor([1.])


In [14]:
sc1 = torch.Tensor([3.])
describe(sc1)

타입 : torch.FloatTensor
크기 : torch.Size([1])
값 : 
tensor([3.])


#### 연산 

In [16]:
# 덧셈
sc_add = sc + sc1
describe(sc_add)

타입 : torch.FloatTensor
크기 : torch.Size([1])
값 : 
tensor([4.])


In [17]:
# 뺄셈
sc_sub = sc - sc1
describe(sc_sub)

타입 : torch.FloatTensor
크기 : torch.Size([1])
값 : 
tensor([-2.])


In [18]:
# 곱셈(아다마르 곱)
sc_mul = sc * sc1
describe(sc_mul)

타입 : torch.FloatTensor
크기 : torch.Size([1])
값 : 
tensor([3.])


In [20]:
# 나눗셈
sc_div = sc / sc1
describe(sc_div)

타입 : torch.FloatTensor
크기 : torch.Size([1])
값 : 
tensor([0.3333])


In [21]:
# torch 내장 메소드 이용도 가능
describe(torch.add(sc, sc1))
describe(torch.sub(sc, sc1))
describe(torch.mul(sc, sc1))
describe(torch.div(sc, sc1))

타입 : torch.FloatTensor
크기 : torch.Size([1])
값 : 
tensor([4.])
타입 : torch.FloatTensor
크기 : torch.Size([1])
값 : 
tensor([-2.])
타입 : torch.FloatTensor
크기 : torch.Size([1])
값 : 
tensor([3.])
타입 : torch.FloatTensor
크기 : torch.Size([1])
값 : 
tensor([0.3333])


### Vector

#### 텐서 만들기

In [24]:
vec1 = torch.tensor([1., 2., 3.])
describe(vec1)

타입 : torch.FloatTensor
크기 : torch.Size([3])
값 : 
tensor([1., 2., 3.])


In [26]:
vec2 = torch.tensor([1,2,3], dtype=int32)
describe(vec2)

NameError: name 'int32' is not defined