## Affine Functions with 1 Feature

### Affine Function

In [5]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.layers import Dense

x = tf.constant([[10.]]) # input setting
print(x)
dense = Dense(units=1, activation='linear') # an affine function

y_tf = dense(x) # forward propagation + params initialization
print(y_tf)

W, B = dense.get_weights() # get weight, bias
print(W, B)
print()
print('***** Input/Weight/Bias *****')
print(f"x : {x.shape}\n{x.numpy()}\n")
print(f"W : {W.shape}\n{W}\n")
print(f"B : {B.shape}\n{B}\n")

tf.Tensor([[10.]], shape=(1, 1), dtype=float32)
tf.Tensor([[7.486018]], shape=(1, 1), dtype=float32)
[[0.7486018]] [0.]

***** Input/Weight/Bias *****
x : (1, 1)
[[10.]]

W : (1, 1)
[[0.7486018]]

B : (1,)
[0.]



In [6]:
y_man = tf.linalg.matmul(x, W) + B # forward propagation(manual)

In [9]:
y_man.numpy()

array([[7.486018]], dtype=float32)

In [10]:
print('***** Outputs *****')
print(f'y(tensorflow) : {y_tf.shape}\n{y_tf.numpy()}\n')
print(f'y(Manual) : {y_man.shape}\n{y_man.numpy()}\n')

***** Outputs *****
y(tensorflow) : (1, 1)
[[7.486018]]

y(Manual) : (1, 1)
[[7.486018]]



### Params Initialization

In [16]:
from tensorflow.keras.initializers import Constant

x = tf.constant([[10.]]) # input setting
# tensorflow는 기본적으로 float32를 기본 자료형으로 하기때문에 데이터를 넣을 때 .을 붙이는걸 습관화 하자
#weight/bias setting
w, b = tf.constant(10.), tf.constant(20.)
w_init, b_init = Constant(w), Constant(b)
# print(w_init, b_init)

# an affine function
dense = Dense(units=1,
                         activation='linear',
                          kernel_initializer=w_init,
                          bias_initializer=b_init)
y_tf = dense(x)
print(y_tf)
W, B = dense.get_weights()

print(W, W.shape)
print(B, B.shape)

tf.Tensor([[120.]], shape=(1, 1), dtype=float32)
[[10.]] (1, 1)
[20.] (1,)


## Affine Functions with n Features

### Affine Fuctions with n Features

In [17]:
import tensorflow as tf
from tensorflow.keras.layers import Dense

x = tf.random.uniform(shape=(1,10))
print(x.shape, '\n', x)

(1, 10) 
 tf.Tensor(
[[0.37992907 0.16473639 0.9290209  0.7844627  0.5272888  0.8083979
  0.6655743  0.63860893 0.19750333 0.6292448 ]], shape=(1, 10), dtype=float32)


In [19]:
dense = Dense(units=1)

y_tf = dense(x)
W, B = dense.get_weights()
y_man = tf.linalg.matmul(x, W) + B

print('***** Input/Weight/Bias *****')
print(f"x : {x.shape}\n{x.numpy()}\n")
print(f"W : {W.shape}\n{W}\n")
print(f"B : {B.shape}\n{B}\n")

print('***** Outputs *****')
print(f'y(tensorflow) : {y_tf.shape}\n{y_tf.numpy()}\n')
print(f'y(Manual) : {y_man.shape}\n{y_man.numpy()}\n')

***** Input/Weight/Bias *****
x : (1, 10)
[[0.37992907 0.16473639 0.9290209  0.7844627  0.5272888  0.8083979
  0.6655743  0.63860893 0.19750333 0.6292448 ]]

W : (10, 1)
[[-0.46131665]
 [-0.43235138]
 [ 0.07701409]
 [ 0.33648115]
 [-0.25945753]
 [ 0.19401598]
 [-0.5877136 ]
 [ 0.14931482]
 [ 0.1613028 ]
 [-0.26248598]]

B : (1,)
[0.]

***** Outputs *****
y(tensorflow) : (1, 1)
[[-0.32007736]]

y(Manual) : (1, 1)
[[-0.32007736]]

