## Activation Functions

### Activation Layers

In [11]:
import tensorflow as tf
from tensorflow.math import exp, maximum
from tensorflow.keras.layers import Activation

x = tf.random.normal(shape=(1,5)) # input setting

sigmoid = Activation('sigmoid')
tanh = Activation('tanh')
relu = Activation('relu')

# forward propagtion (using tensorflow)
y_sigmoid_tf = sigmoid(x)
y_tanh_tf = tanh(x)
y_relu_tf = relu(x)

# forward propagation (using manual)
y_sigmoid_man = 1/(1 + exp(-x))
y_tanh_man = (exp(x) - exp(-x))/(exp(x) + exp(-x))
y_relu_man = maximum(x, 0)

print(f'x : {x.shape} / {x.numpy()}')
print(f'Sigmoid(tensorflow) : {y_sigmoid_tf.shape} \n {y_sigmoid_tf.numpy()}')
print(f'Sigmoid(manual) : {y_sigmoid_man.shape} \n {y_sigmoid_man.numpy()}')
print(f'Tanh(tensorflow) : {y_tanh_tf.shape} \n {y_tanh_tf.numpy()}')
print(f'Tanh(manual) : {y_tanh_man.shape} \n {y_tanh_man.numpy()}')
print(f'ReLU(tensorflow) : {y_relu_tf.shape} \n {y_relu_tf.numpy()}')
print(f'ReLU(manual) : {y_relu_man.shape} \n {y_relu_man.numpy()}')

x : (1, 5) / [[ 0.24473165  0.40281045 -0.35701185 -0.6260547   1.9396616 ]]
Sigmoid(tensorflow) : (1, 5) 
 [[0.56087935 0.59936273 0.4116831  0.34840566 0.87431496]]
Sigmoid(manual) : (1, 5) 
 [[0.56087935 0.59936273 0.4116831  0.34840566 0.87431496]]
Tanh(tensorflow) : (1, 5) 
 [[ 0.23995996  0.38235113 -0.34257928 -0.5553296   0.95950717]]
Tanh(manual) : (1, 5) 
 [[ 0.23995999  0.38235113 -0.34257928 -0.5553296   0.95950717]]
ReLU(tensorflow) : (1, 5) 
 [[0.24473165 0.40281045 0.         0.         1.9396616 ]]
ReLU(manual) : (1, 5) 
 [[0.24473165 0.40281045 0.         0.         1.9396616 ]]


### Activation in Dense Layer

In [12]:
import tensorflow as tf
from tensorflow.keras.layers import Dense, Activation

In [15]:
x = tf.random.normal(shape=(1,5)) # input setting

# artificial neurons
dense_sigmoid = Dense(units=1 , activation='sigmoid')
dense_tanh = Dense(units=1, activation='tanh')
dense_relu = Dense(units=1, activation='relu')

# forward propagation(tensorflow)
y_sigmoid = dense_sigmoid(x)
y_tanh = dense_tanh(x)
y_relu = dense_relu(x)

print(f'AN with Sigmoid : {y_sigmoid.shape}\n{y_sigmoid.numpy()}')
print(f'AN with tanh : {y_tanh.shape}\n{y_tanh.numpy()}')
print(f'AN with relu : {y_relu.shape}\n{y_relu.numpy()}')

# forward propagation(manual)
print('\n====================\n')

W, B = dense_sigmoid.get_weights()
z = tf.linalg.matmul(x,W) + B
a = 1 / (1+ exp(-z))
print(f'Activation Value(tensorflow) : {y_sigmoid.shape}\n{y_sigmoid.numpy()}')
print(f'Activation Value(manual) : {a.shape}\n{a.numpy()}')

AN with Sigmoid : (1, 1)
[[0.31202427]]
AN with tanh : (1, 1)
[[0.8543648]]
AN with relu : (1, 1)
[[0.2093778]]


Activation Value(tensorflow) : (1, 1)
[[0.31202427]]
Activation Value(manual) : (1, 1)
[[0.31202427]]


## Artificial Neurons

### Artificial Neurons

In [21]:
import tensorflow as tf
from tensorflow.keras.layers import Dense
from tensorflow.math import exp, maximum

# activation = 'sigmoid'
# activation = 'tanh'
activation = 'relu'

x = tf.random.uniform(shape=(1,10))

dense = Dense(units=1, activation=activation)

y_tf = dense(x)
W, B = dense.get_weights()

# calculate activation value manually
y_man = tf.linalg.matmul(x, W) + B
if activation == 'sigmoid':
    y_man = 1 / (1 + exp(-y_man))
elif activation == 'tanh':
    y_man = (exp(y_man) - exp(-y_man)) / (exp(y_man) + exp(-y_man))
elif activation == 'relu':
    y_man = maximum(y_man ,0)
    
print('Activation : ', activation)
print(f'y_tf : {y_tf.shape}\n{y_tf.numpy()}')
print(f'y_man : {y_man.shape}\n{y_man.numpy()}')

Activation :  relu
y_tf : (1, 1)
[[0.]]
y_man : (1, 1)
[[0.]]


## Minibatches

### Shapes of Dense Layers

In [23]:
import tensorflow as tf
from tensorflow.keras.layers import Dense

N, n_feature = 8, 10 # N이 미니배치의 사이즈인데 이것은 가중치와 편향(bias)에 영향을 미치지 않는다.
x = tf.random.normal(shape=(N, n_feature)) # generate minibatch
print(x.shape)

dense = Dense(units=1, activation='relu') # an AN
y = dense(x) # forward propagation

W, B = dense.get_weights() # get weights/bias

# print results
print(f"Shape of x : {x.shape}")
print(f'Shape of W : {W.shape}')
print(f'Shape of B : {B.shape}')

(8, 10)
Shape of x : (8, 10)
Shape of W : (10, 1)
Shape of B : (1,)


### Output Calculation

In [25]:
import tensorflow as tf
from tensorflow.keras.layers import Dense

N, n_feature = 8, 10 # set input params
x = tf.random.normal(shape=(N, n_feature)) # generate minibatch

dense = Dense(units=1, activation='sigmoid') # an AN
y_tf = dense(x) # forward propagation(tensorflow)

W, B = dense.get_weights() # get weights/bias

y_man = tf.linalg.matmul(x, W) + B # forward propagation (manual)
y_man = 1 / (1 + exp(-y_man))
# print results
print(f'Output(tensorflow) : {y_tf.numpy()}')
print(f'Output(manual) : {y_man.numpy()}')

Output(tensorflow) : [[0.32297447]
 [0.18615751]
 [0.3721323 ]
 [0.4763674 ]
 [0.50935024]
 [0.5069301 ]
 [0.520999  ]
 [0.5456856 ]]
Output(manual) : [[0.32297447]
 [0.18615751]
 [0.3721323 ]
 [0.4763674 ]
 [0.50935024]
 [0.5069301 ]
 [0.520999  ]
 [0.5456856 ]]
