In [1]:
print('안녕 코랩')

안녕 코랩


In [2]:
# 모델의 성능을 평가하기 위한 패키지 임포트
from sklearn.metrics import classification_report, confusion_matrix

# data set을 training set과 test set으로 분리할 서브패키지 불러들임
from sklearn.model_selection import train_test_split

# 의사결정 트리 알고리즘 서브 패키지를 불러들임
from sklearn.tree import DecisionTreeClassifier

# Ipython 내에 정보를 보여주는 도구용 공용 API
# Image : raw 데이터가 있는 PNG, JPEG 이미지 객체를 만드는 모듈
from IPython.display import Image
import cv2

import pandas as pd
import numpy as np

import pydotplus
import os

In [3]:
df = pd.read_csv('./text/1.머신러닝/workspace/playtennis.csv')

In [4]:
df

Outlook Temperature Humidity    Wind PlayTennis
0      Sunny         Hot     High    Weak         No
1      Sunny         Hot     High  Strong         No
2   Overcast         Hot     High    Weak        Yes
3       Rain        Mild     High    Weak        Yes
4       Rain        Cool   Normal    Weak        Yes
5       Rain        Cool   Normal  Strong         No
6   Overcast        Cool   Normal  Strong        Yes
7      Sunny        Mild     High    Weak         No
8      Sunny        Cool   Normal    Weak        Yes
9       Rain        Mild   Normal    Weak        Yes
10     Sunny        Mild   Normal  Strong        Yes
11  Overcast        Mild     High  Strong        Yes
12  Overcast         Hot   Normal    Weak        Yes
13      Rain        Mild     High  Strong         No

In [5]:
df['Outlook'] = df['Outlook'].replace('Sunny', 0)
df['Outlook'] = df['Outlook'].replace('Overcast', 1)
df['Outlook'] = df['Outlook'].replace('Rain', 2)

In [6]:
df['Temperature'] = df['Temperature'].replace('Hot', 1)
df['Temperature'] = df['Temperature'].replace('Mild', 2)
df['Temperature'] = df['Temperature'].replace('Cool', 3)

df['Humidity'] = df['Humidity'].replace('High', 1)
df['Humidity'] = df['Humidity'].replace('Normal', 2)

df['Wind'] = df['Wind'].replace('Weak', 1)
df['Wind'] = df['Wind'].replace('Strong', 2)

df['PlayTennis'] = df['PlayTennis'].replace('No', 1)
df['PlayTennis'] = df['PlayTennis'].replace('Yes', 2)

In [32]:
X = np.array(df[list(df.columns)[0:4]])
y = np.array(df[list(df.columns)[4]])

IndexError: list index out of range

In [8]:
X

array([[0, 1, 1, 1],
       [0, 1, 1, 2],
       [1, 1, 1, 1],
       [2, 2, 1, 1],
       [2, 3, 2, 1],
       [2, 3, 2, 2],
       [1, 3, 2, 2],
       [0, 2, 1, 1],
       [0, 3, 2, 1],
       [2, 2, 2, 1],
       [0, 2, 2, 2],
       [1, 2, 1, 2],
       [1, 1, 2, 1],
       [2, 2, 1, 2]], dtype=int64)

In [33]:
y.reshape(-1)

array([1, 1, 2, 2, 2, 1, 2, 1, 2, 2, 2, 2, 2, 1], dtype=int64)

In [34]:
arr = np.array([[1,2,3], [4,5,6], [7,8,9]])

In [40]:
print(arr.reshape(-1))

[1 2 3 4 5 6 7 8 9]


In [10]:
X_train, X_test, y_train, y_test = train_test_split(X, y)

In [11]:
dt_clf = DecisionTreeClassifier()
dt_clf = dt_clf.fit(X_train, y_train)

In [12]:
dt_prediction = dt_clf.predict(X_test)

In [13]:
from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test, dt_prediction)

In [14]:
print('정확도 : ', accuracy)

정확도 :  0.75


In [15]:
feature_names = df.columns.tolist()
feature_names = feature_names[0:4]

In [16]:
target_name = np.array(['Play No', 'Play Yes'])

In [17]:
from sklearn import tree

In [18]:
dt_dot_data = tree.export_graphviz(dt_clf, out_file=None,
                                              feature_names= feature_names,
                                              class_names = target_name,
                                              filled=True, rounded=True,
                                              special_characters=True)

In [42]:
dt_dot_data = tree.export_graphviz(dt_clf, out_file = None,
                                   feature_names = feature_names,
                                   class_names = target_name,
                                   filled = True, rounded = True,
                                special_characters = True)

In [43]:
dt_graph = pydotplus.graph_from_dot_data(dt_dot_data)

In [44]:
Image(dt_graph.create_png())

InvocationException: GraphViz's executables not found

In [25]:
dt_dot_data= tree.export_graphviz(dt_clf, 
                out_file='tree.dot',
                feature_names = feature_names,
                class_names = target_name,
               )

트리의 내용 조회(문자료)