In [1]:
import numpy as np

### 1차원 배열

In [2]:
A = np.array([1,2,3,4])
print(A)

[1 2 3 4]


In [3]:
np.ndim(A)

1

In [4]:
A.shape

(4,)

In [5]:
A.shape[0]

4

### 2차원 배열

In [6]:
B = np.array([[1,2], [3,4], [5,6]])
print(B)

[[1 2]
 [3 4]
 [5 6]]


In [7]:
np.ndim(B)

2

In [9]:
B.shape

(3, 2)

In [17]:
B.T.shape[0]

2

### 행렬의 곱

In [19]:
A = np.array([[1,2], [3,4]])
A.shape

(2, 2)

In [20]:
B = np.array([[5,6], [7,8]])
B.shape

(2, 2)

In [21]:
np.dot(A, B)

array([[19, 22],
       [43, 50]])

In [22]:
A@B

array([[19, 22],
       [43, 50]])

### 신경망에서의 행렬 곱

In [23]:
X = np.array([1,2]) # x1 = 1, x2 = 2
X.shape

(2,)

In [24]:
W = np.array([[1,3,5], [2,4,6]]) # 가중치 순서순
print(W)

[[1 3 5]
 [2 4 6]]


In [25]:
W.shape

(2, 3)

In [27]:
Y = X@W
print(Y)

[ 5 11 17]
