## Conv Layers

### Shapes of Conv Layers

In [19]:
import tensorflow as tf
import numpy as np
from tensorflow.keras.layers import Conv2D

N, n_H, n_W, n_C = 32, 28, 28, 5
n_filter = 10
k_size = 3

images = tf.random.uniform(minval=0, maxval=1, shape = ((N, n_H, n_W, n_C)))

print(images.shape)

conv = Conv2D(filters=n_filter, kernel_size=k_size)

y = conv(images)
W, B = conv.get_weights()

print(W.shape)
print(B.shape)
print(y.shape)

(32, 28, 28, 5)
(3, 3, 5, 10)
(10,)
(32, 26, 26, 10)


### Correlation Calculation

In [20]:
import tensorflow as tf
import numpy as np
from tensorflow.keras.layers import Conv2D

N, n_H, n_W, n_C = 1, 5, 5, 1
n_filter = 1
k_size = 3

images = tf.random.uniform(minval=0, maxval=1, shape = ((N, n_H, n_W, n_C)))

print(images.shape)

conv = Conv2D(filters=n_filter, kernel_size=k_size)

y = conv(images)
W, B = conv.get_weights()

print(W.shape)
print(B.shape)
print(y.shape)
print("Y(tensorflow) : \n", y.numpy().squeeze())

images = images.numpy().squeeze()
W = W.squeeze()

y_man = np.zeros(shape=(n_H - k_size + 1, n_W - k_size + 1))
for i in range(n_H - k_size + 1):
    for j in range(n_W - k_size + 1):
        window = images[i : i+k_size, j : j+k_size]
        y_man[i, j] = np.sum(window*W) + B
print('Y(manual) : \n', y_man)



(1, 5, 5, 1)
(3, 3, 1, 1)
(1,)
(1, 3, 3, 1)
Y(tensorflow) : 
 [[-0.40100697  0.08786326 -0.39688262]
 [-0.14414974  0.05167706 -0.51198244]
 [-0.28092736 -0.36168802 -0.31240967]]
Y(manual) : 
 [[-0.40100694  0.08786324 -0.39688259]
 [-0.14414972  0.05167701 -0.51198244]
 [-0.2809273  -0.36168799 -0.31240964]]


### Correlation with n-channel

In [22]:
# 3 channel
N, n_H, n_W, n_C = 1, 5, 5, 3
n_filter = 1
k_size = 3

images = tf.random.uniform(minval=0, maxval=1, shape = ((N, n_H, n_W, n_C)))

# print(images.shape)

conv = Conv2D(filters=n_filter, kernel_size=k_size)

y = conv(images)
W, B = conv.get_weights()

print("Y(tensorflow) : \n", y.numpy().squeeze())

images = images.numpy().squeeze()
W = W.squeeze()

y_man = np.zeros(shape=(n_H - k_size + 1, n_W - k_size + 1))
for i in range(n_H - k_size + 1):
    for j in range(n_W - k_size + 1):
        window = images[i : i+k_size, j : j+k_size, :]
        y_man[i, j] = np.sum(window*W) + B
print('Y(manual) : \n', y_man)

Y(tensorflow) : 
 [[-1.0690262  -0.78065115  0.11340525]
 [-0.194404   -0.28601158 -0.28410292]
 [-0.53984445  0.10284387 -0.74632025]]
Y(manual) : 
 [[-1.06902623 -0.78065121  0.11340525]
 [-0.19440407 -0.28601155 -0.28410298]
 [-0.53984445  0.10284397 -0.74632031]]
